import { defineCollection, reference, z } from 'astro:content';
import { glob } from 'astro/loaders';

const insights = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/insights' }),
  schema: z.object({
    title: z.string(),
    date: z.coerce.date(),
    og_title: z.string().optional(),
    og_image: z.string().url().optional(), // generated by og-images.mjs at build time
    summary: z.string().optional(), // AI-generated at build time
    category: z.string(), // Strategy | Psychology | Technology | Business | Methodology
    status: z.enum(['draft', 'published']),
  }),
});

const services = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/services' }),
  schema: z.object({
    // ── Existing fields ──────────────────────────────────────────────────
    title:              z.string(),
    status:             z.enum(['active', 'retired']),
    price:              z.string(),
    format:             z.string(),
    cta_label:          z.string(),
    featured_use_cases: z.array(reference('use-cases')).default([]),
 
    // ── New fields ───────────────────────────────────────────────────────
 
    /** Filter tags for the archive type-nav. One or more of these values.
     *  e.g. ["individual"] or ["individual", "team"] */
    type: z.array(
      z.enum(['individual', 'team', 'workshop', 'cohort'])
    ).default(['individual']),
 
    /** Shown in the hero badge: "Discovery Engagement · Individual or Team" */
    engagement_type: z.string().optional(),
 
    /** Short italic gold one-liner under the title */
    one_liner: z.string().optional(),
 
    /** 2–3 sentence hero description (longer than summary) */
    description: z.string().optional(),
 
    /** Stats strip values */
    duration:     z.string().optional(),   // "1–3 days"
    group_size:   z.string().optional(),   // "Individual" / "6–20"
    delivery:     z.string().optional(),   // "On-site, remote, or both"
    suitable_for: z.string().optional(),   // "Leaders, founders, teams"
 
    /** Pull quote for the detail page body */
    pull_quote: z.string().optional(),
 
    /** Outcomes list — "What you leave with" section */
    outcomes: z.array(z.object({
      name:        z.string(),
      description: z.string(),
    })).default([]),
 
    /** Who it's for cards */
    for_profiles: z.array(z.object({
      title: z.string(),
      body:  z.string(),
    })).default([]),
 
    /** Not-for disclaimer */
    not_for: z.string().optional(),
 
    /** OG / SEO */
    og_title: z.string().optional(),
    og_image: z.string().url().optional(),
  }),
});

const useCases = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/use-cases' }),
  schema: z.object({
 
    // ── Core ──────────────────────────────────────────────────────────────
    title:   z.string(),          // Full case title
    status:  z.enum(['published', 'draft']),
    date:    z.coerce.date(),
 
    // ── Content model ──────────────────────────────────────────────────────
 
    /** The broad organisational concern this case examines.
     *  Shown as a category label on cards and in the hero.
     *  e.g. "Cybersecurity", "Leadership Alignment", "Digital Transformation" */
    topic: z.string(),
 
    /** The specific situation / scenario this case is built around.
     *  1–2 sentences. Concrete, not abstract.
     *  Shown as the italic deck on cards and in the archive.
     *  e.g. "A mid-size financial firm invests €2M in security tooling
     *        and suffers a breach six months later." */
    scenario: z.string(),
 
    /** Short summary for SEO / meta description */
    summary: z.string().optional(),
 
    // ── Domain / applicability ─────────────────────────────────────────────
    /** Primary filter category (matches archive filter buttons) */
    category: z.string(),
 
    /** Additional domain tags beyond the primary category */
    domain: z.array(z.string()).default([]),
 
    /** Who this applies to — shown in sidebar and card */
    applies_to: z.string().optional(),   // e.g. "All industries"
 
    /** Organisation size context */
    org_size: z.string().optional(),     // e.g. "Mid-market upward"
 
    // ── Services ──────────────────────────────────────────────────────────
    /** Primary service slug — links to /services/[slug] */
    primary_service: z.string().optional(),    // e.g. "assumption-hunting"
 
    /** Secondary service slug */
    secondary_service: z.string().optional(), // e.g. "burn-the-box"
 
    // ── Hero stats strip ──────────────────────────────────────────────────
    /** Key data points shown in the hero stats strip */
    stats: z.array(z.object({
      value: z.string(),   // e.g. "85%"
      label: z.string(),   // e.g. "of breaches involve a human component"
    })).default([]),
 
    // ── OG / SEO ──────────────────────────────────────────────────────────
    og_title: z.string().optional(),
    og_image: z.string().url().optional(),
  }),
});

const library = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/library' }),
  schema: z.object({
 
    title:      z.string(),
    type:       z.enum(['bias', 'structure', 'method']),
    definition: z.string(),
    summary:    z.string().optional(),
 
    first_described: z.string().optional(),
    applies_to:      z.string().optional(),
    risk_level:      z.string().optional(),
 
    tags: z.array(z.string()).default([]),
 
    /** Slugs of related library entries.
     *  Title, type, and definition are resolved from those files at build time. */
    related_entries: z.array(z.string()).default([]),
 
    /** References to use cases or insights where this concept appears.
     *  Title is resolved from the respective collection at build time.
     *  `note` is an optional sentence describing how the concept appears. */
    in_practice: z.array(z.object({
      type: z.enum(['use-case', 'insight']),
      slug: z.string(),
      note: z.string().optional(),
    })).default([]),
 
    og_title: z.string().optional(),
  }),
});

const faqs = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/faqs' }),
  schema: z.object({
    question: z.string(),
    answer: z.string(),
    category: z.string(), // Services | Methodology | Working Together | Technical
    order: z.number(),
  }),
});

const podcast = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/podcast' }),
  schema: z.object({
    title:          z.string(),
    date:           z.coerce.date(),
    episode_number: z.number(),
    summary:        z.string().optional(),
    description:    z.string().optional(),
    og_title:       z.string(),
    og_image:       z.string().optional(),
    episode_id:     z.string().optional(),        // RSS <guid>
    audio_url:      z.string().url(),             // ← RSS <enclosure url> — direct MP3
    artwork_url:    z.string().url().optional(),  // RSS <itunes:image href>
    spotify_url:    z.string().url().optional(),  // open.spotify.com/episode/... (external link only)
    youtube_url:    z.string().url().optional(),  // YouTube watch URL
    duration:       z.string().optional(),        // RSS <itunes:duration> e.g. "00:47:23"
    category:       z.string(),
    status:         z.enum(['draft', 'published']),
    publish_date:   z.coerce.date().optional(),
  }),
});

export const collections = {
  insights,
  services,
  'use-cases': useCases,
  library,
  faqs,
  podcast,
};
